on:
  push:
    branches:
      - main
  pull_request:

name: Clippy check

permissions:
  contents: read

jobs:
  clippy_check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Run Clippy
        run: cargo clippy --manifest-path src-tauri/Cargo.toml --all-targets -- -D warnings
